### ISSUE TITLE
Feature Request: String

### ISSUE THREAD

**Issue by sokcuri** [ItalyPaleAle/arraybuffer#1]
Sometime needs to convert an ArrayString to a raw string.
It would be very helpful if the ArrayBuffer-encoding library could handle it.

**Comment by ItalyPaleAle** [comment]
Hi @sokcuri! You can convert from an ArrayBuffer (or one of its views like Uint8Array) with a one-liner (assuming `ab` is an ArrayBuffer):

```js
const str = (new TextDecoder('utf-8')).decode(ab)
```

I think I would prefer to keep this library lean and focused on buffers to avoid the scope expanding too much!

**Comment by sokcuri** [comment]
Thanks for comments! I'll try it TextDecoder.
